# docker-compose configuration

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: contextforge
    restart: unless-stopped
    ports:
      - "3000:5000"
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://user:password@mongodb:27017/contextforge?authSource=admin
      - JWT_SECRET=contextforge-secret-key-for-testing
      - AI_PROVIDER=mock
      - USE_REAL_AI=false
      - CLIENT_URL=http://localhost:3000
      - SERVER_URL=http://localhost:5000
      # Firebase config will be injected as a single environment variable
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
    depends_on:
      - mongodb
    networks:
      - contextforge-network

  mongodb:
    image: mongo:6.0
    container_name: contextforge-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=contextforge
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - contextforge-network

networks:
  contextforge-network:
    driver: bridge

volumes:
  mongo-data: