version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: context-generator
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - context-generator-network

  mongodb:
    image: mongo:6.0
    container_name: context-generator-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=context-generator
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - context-generator-network

networks:
  context-generator-network:
    driver: bridge

volumes:
  mongo-data: